import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, PT_Mono, Palette_Mosaic } from "next/font/google";
import "./globals.css";
import { Link } from "lucide-react";
import { Button } from "radix-ui/toolbar";
import CardDemo from "./card_demo/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pt_Mono = PT_Mono({
  subsets: ['cyrillic'],
  weight: '400'
})
const palette_mosaic = Palette_Mosaic({
  subsets: ["latin"],
  weight: '400'
})

const inter = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function NavBar(){
  return(
    
  <div>  
      <Link
        href = {'/button_demo'}
        className = "hover:text-red-500"
      >
        Button Demo
      </Link>
      
      <Link
         href= {'/card_demo'}
         className = "hover:text-red-500"
      >
        Card Demo
      </Link>
  </div>  
   )
  }


export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${pt_Mono.className} h-full antialiased`}
    >
      <NavBar/>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
